# Generated by Django 3.2.13 on 2022-06-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Организация')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Клиент', to='client.client')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'unique_together': {('name', 'client_name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Счет', to='client.organization')),
            ],
            options={
                'verbose_name': 'счет',
                'verbose_name_plural': 'счета',
                'unique_together': {('client_org', 'number')},
            },
        ),
    ]
