# Generated by Django 3.2.13 on 2022-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220623_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
